### ISSUE TITLE
strange issue: importing a vrm no longer creates a FileName.vrm.textures folder

### ISSUE THREAD

**Issue by hanetzer** [Yusarina/Cats-Blender-Plugin-Unofficial-#47]
Mistakenly filed this issue https://github.com/absolute-quantum/cats-blender-plugin/issues/666 here

Didn't change anything of note, but now importing a vrm, with 'extract textures into folder' checked, no longer creates such a folder, even on a vrm file which was previously known to work. Its honestly driving me crazy.

* blender 3.6.5 as packaged by gentoo linux.
* VRM_Addon_for_Blender-2_20_28.zip
* Cats-Blender-Plugin-Unofficial3.6.6.0.zip
* material-combiner-addon-master.zip (yes I know that's not terribly useful, sorry).
Thank you.

**Comment by Yusarina** [comment]
Hi there,

I have to double check the code but I pretty sure cats doesn't do anything much when it comes to importing a vrm file with as this is done via the VRM Addon.

Please disabled cats and import the model via file > Import > VRM. If you still have the same issue then this isn't anything to do with cats and is to do with the VRM addon instead and you will have to report the issue there.

If the issue resolves itself when disabling cats I will look into it further.

Thanks!

**Comment by Yusarina** [comment]
Hi there,

I just testing this myself and I have the same issue with or without cats, I believe this is most likely not a cats issue and is an issue with the VRM addon, unless you have different results to me please report this issue to them here: https://github.com/saturday06/VRM-Addon-for-Blender/issues

Thanks!

**Comment by Yusarina** [comment]
Hi there, 

I can 100% confirm this is bug introduce into the VRM addon, I downgraded to version 2.20.20 of the addon and the textures folder is now created. I would advise for the time being to downgrade to that version of the addon as well.

**Comment by hanetzer** [comment]
Damn, you move fast. Thanks, I'll file that issue with them. I managed to bodge it into working in some ugly manner but its all good.
