### ISSUE TITLE
return feature req: 'set up eye tracking from avatars 2.0'

### ISSUE THREAD

**Issue by hanetzer** [Yusarina/Cats-Blender-Plugin-Unofficial-#55]
I occasionally do some work on vroid-originated avatars, and in CVR (Chillout VR), if one enables eye tracking without using the above named feature on the avatar first, the avatar will have lazy/crazy eyes (far too large a range of motion and such). This assumes having imported the *.vrm file using that addon.

I can't speak as to the vr experience with eye tracking without this modification, as I'm currently a desktop player and none of the people I've done this sort of thing for have vr headsets that do that.

**Comment by Yusarina** [comment]
Hi there, 

I was removed as VRC no longer needed the method however if CVR still needs it I can add it back in, however it might not be completed today, it most likely be tomorrow.

**Comment by Yusarina** [comment]
This has now been released into version 3.6.6.3 for Blender 3.6 and version 4.0.4.2 for Blender 4.0.

Closed this request, if there anything else to do with this request feel free to re-open.

Thanks!
