### ISSUE TITLE
MMD shapekey 'standard translations'

### ISSUE THREAD

**Issue by hanetzer** [Yusarina/Cats-Blender-Plugin-Unofficial-#74]
Ello again. So having since learned more about how avatars are handled generally, I've
learned that many of the facial blend shapes tend to use standard japanese names from
the software MMD. Given this, one could prepare a sort of rosetta stone of these blend
shapes ahead of time for use in the translation function.

**Comment by Yusarina** [comment]
Hi There,

People can now provide translations for cats via this repo: https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-translations

You can add translations to the https://github.com/Yusarina/Cats-Blender-Plugin-Unofficial-translations/blob/3.6-4.0-translations/dictionary.json via a pull request. (I will pull any translations to the 4.1 branch at a later date).

I am planning to have cats either download the latest translations on startup from the repo or atleast have a button where the user can download them.
